sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t youssefh/docker-react -f Dockerfile.dev .

script:
  - docker run youssefh/docker-react npm run test -- --coverage
