sudo: required
services:
  - docker

before_install:
  - gem install bundler
  - docker build -t youssefh/docker-react -f Dockerfile.dev .

script:
  - docker run youssefh/docker-react npm run test -- --coverage
